# site settings
title: Fish Pond 
subtitle: The band
email: contact@fishpond.band
description: The website for the band Fish Pond
baseurl: "" # the subpath of your site, e.g. /blog
url: https://fishpond.band # the base hostname & protocol for your site
author: Jack D
street_address: 
city: 
state: 
zip_code: 
country: Scotland
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://instagram.com/fishpond.band
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
